### ISSUE TITLE
Unable to read beyond the end of the stream

### ISSUE THREAD

**Issue by sakurahana90** [arcusmaximus/CSystemTools#3]
Hello and thank you for this CSystem Tools.

I want to ask about this tools. I tried this tools on Yumekoi Tensei (https://vndb.org/v1036) and I met this warning below after I send unpack command to Arc01.dat and Arc04.dat which should be contains scenario index and contents.

Unable to read beyond the end of the stream.

Can you help me to fix this or is there something to change in the tools config or something?

Thank you

**Comment by arcusmaximus** [comment]
Fixed in version 1.1. Note that the syntax of the `pack` command has changed (needs a version number now).

**Comment by sakurahana90** [comment]
First I want to thank you so much for the tools' update. 

I've tried it and after using the updated VNTranslationTool and it worked great until the point I can extract the script to the xlsx. 

The problem starts when I inserted the translated line using xlsx and pack it again using the version number (which in my case is 22). The game can run and play the opening but after I clicked the start button on the game, the game went blank and before long, it closed by itself without any warning. I also tried using Locale Emulator but nothing's different. 

I wanted to use VNTextProxy but unfortunately there is no single file in the game folder with .dll extension so I couldn't reference proxy .dll to the game.

Hope you can guide me here. Thank you.
